### ISSUE TITLE
Installing on MacOS

### ISSUE THREAD

**Issue by aaronsingline** [ServiceInnovationLab/openfisca-aotearoa#23]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:

I ran through first steps of installation but got stuck on "pew new openfisca --python=python2.7"

### Here is what I expected to happen: 

It should have installed.

### Here is what actually happened:

Running virtualenv with interpreter /usr/local/bin/python2.7
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
New python executable in /var/root/.local/share/virtualenvs/openfisca/bin/python2.7
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Library/Python/2.7/site-packages/virtualenv.py", line 1233, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/opt/python/bin/python2.7'

### Here is data (or links to it) that can help you reproduce this issue:

This is on MacOS 10.13.4
Python 2.7.10
pip 10.0.1

Python was installed by using Homebrew.

## Context

I identify more as a:

- Developer/Hobbyist

**Comment by RantyDave** [comment]
I've had occasional grief with the homebrew Python - try the 'real' installer from https://www.python.org/ftp/python/2.7.15/python-2.7.15-macosx10.9.pkg

**Comment by Br3nda** [comment]
Sorry i don't have macos - none of our team do
let us know if @RantyDave's solution works- a readme update would be useful.

This repo is the Aotearoa legislation rule sets -- we can fix instructions here, but if we should also copy those upstream to the country template.

**Comment by aaronsingline** [comment]
Thanks for that.  I’ll try the suggestion when I get some free time.  Installing an up to date python was a bit of a pain at the time I last tried to do it on MacOS. :). I’ll revisit it and if it still causes issues I’ll post more info in the Issues section of the repo (unless you’d prefer it elsewhere).

Thanks for all the hard work. :)

--
Aaron Singline
IT Support / Developer
Physiology Department | Te Tari Matai Whaiaroaro
Otago University | Te Whare Wānanga o Otago
